# Generated by Django 5.2.7 on 2026-02-22 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillmatch',
            unique_together={('user', 'matched_user', 'skill')},
        ),
        migrations.AddIndex(
            model_name='skillmatch',
            index=models.Index(fields=['user', 'status'], name='dashboard_s_user_id_4e36bd_idx'),
        ),
        migrations.AddIndex(
            model_name='skillmatch',
            index=models.Index(fields=['matched_user', 'status'], name='dashboard_s_matched_feb58e_idx'),
        ),
    ]
